boot_command=["<wait3>c<wait3>","linux /casper/vmlinuz quiet autoinstall net.ifnames=0 biosdevname=0 ip=dhcp ipv6.disable=1 ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ <enter>","initrd /casper/initrd <enter>","boot <enter>"]
disk_size="1048576"
http_directory="../extra/hyperv"
iso_checksum_type="sha256"
iso_checksum="45f873de9f8cb637345d6e66a583762730bbea30277ef7b32c9c3bd6700a32b2"
iso_url="../ISO/ubuntu-22.04.4-live-server-amd64.iso"
output_directory="output-ubuntu2204"
provision_script_options="-z false -h true -p false"
ssh_password="password"
ssh_username="ubuntu"
switch_name="Broadcom NetXtreme Gigabit Ethernet #4 - Virtual Switch"
vlan_id=""
vm_name="Azure-Pipelines_Ubuntu"
uefi_file="extrauefi.sh"
